### ISSUE TITLE
daqdb deployment in clould failed (through yaml design upload)

### ISSUE THREAD

**Issue by stalisetty-nisum-com** [oneops/inductor#40]
In Cloud, while we try to deploy daqdb through design yaml upload, seeing the failure with "keyspace-mdb" as follows.

**Observation:**

10.181.7.230 ip is private IP of daqdb compute. Not sure, why it is trying to ssh private ip instead of public ip.

**Log:**

Inductor: 172.31.36.83 (eth0)
### SYNC BASE: /opt/oneops/inductor/circuit-oneops-1/components
Cmd: /usr/bin/rsync -az --force --exclude=*.png --rsh=ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 22 -qi /opt/oneops/inductor/clouds-available/shared/data/de258737-b0f5-465e-b0c8-476e68dbda47 --timeout=30 /opt/oneops/inductor/circuit-oneops-1/components oneops@10.181.7.230:/home/oneops/circuit-oneops-1, Env: null
cmd error: [sender] io timeout after 30 seconds -- exiting

**Comment by mosabua** [comment]
Issue tracking is migrated to Walmart JIRA and https://github.com/oneops/oneops.
