### ISSUE TITLE
Allow inductor to be called from anywhere

### ISSUE THREAD

**Issue by challsted** [oneops/inductor#9]
At the moment, the inductor command must be called from within the inductor directory its effecting.  
Can we add a option to be passed that will tell it which inductor to operate on and an option to tell it which cloud to operate on. 

This could be improved slightly more with the option of it always knowing where the default inductor is, and if no commands were passed to it it should look for 2 things.  

This could be improved more if you added some default logic, so that you can still type `inductor command(s)` from anywhere. If the script could check if its in an inductor directory already, if so preform the asked command on that directory.  
Also, if no options were passed, and its not in an inductor directory, print a small warning to the screen and default to the shared inductor. 

So i could be in ~/ and run `inductor tail` and it would tail the shared inductor. But if i said something like `inductor tail --inductor private --cloud also_private` it would find that inductor and that cloud and preform the tail action on its logs.

**Comment by mosabua** [comment]
Issue tracking is migrated to Walmart JIRA and https://github.com/oneops/oneops.
